### ISSUE TITLE
Malformed version number string Error: (ArgumentError)

### ISSUE THREAD

**Issue by jacobh0** [rodjek/librarian-puppet#130]
Getting the following error when running install:

```
[Librarian] Ruby Version: 2.0.0
[Librarian] Ruby Platform: x86_64-darwin12.3.0
[Librarian] Rubygems Version: 2.0.6
[Librarian] Librarian Version: 0.0.24
[Librarian] Librarian Adapter: puppet
[Librarian] Project: /Users/lordjmann/Drive/Development/D3Bay
[Librarian] Specfile: Puppetfile
[Librarian] Lockfile: Puppetfile.lock
[Librarian] Git: /usr/local/git/bin/git
[Librarian] Git Version: git version 1.7.11
[Librarian] Git Environment Variables:
[Librarian]   (empty)
[Librarian] Pre-Cached Sources:
[Librarian] Post-Cached Sources:
[Librarian]   [:git, "https://github.com/puppetlabs/puppetlabs-apt.git", {}]
[Librarian]   [:git, "https://github.com/puppetlabs/puppetlabs-postgresql.git", {}]
[Librarian] Scheduling apt (>= 0) <https://github.com/puppetlabs/puppetlabs-apt.git#master>
[Librarian] Scheduling postgresql (>= 0) <https://github.com/puppetlabs/puppetlabs-postgresql.git#master>
[Librarian] Resolving apt (>= 0) <https://github.com/puppetlabs/puppetlabs-apt.git#master>
[Librarian]   No known prior constraints
[Librarian]   Checking manifests
[Librarian] Running `/usr/local/git/bin/git reset --hard --quiet` in .tmp/librarian/cache/source/git/c3b3adb5d1295c5d0e8a9fff5cb92427
[Librarian]     --- No output
[Librarian] Running `/usr/local/git/bin/git clean -x -d --force --force` in .tmp/librarian/cache/source/git/c3b3adb5d1295c5d0e8a9fff5cb92427
[Librarian]     --- No output
[Librarian] Running `/usr/local/git/bin/git rev-parse HEAD --quiet` in .tmp/librarian/cache/source/git/c3b3adb5d1295c5d0e8a9fff5cb92427
[Librarian]     --> 3e3de6ee924ea75463e9df4ffdb5712c0e145403
[Librarian] Running `/usr/local/git/bin/git fetch origin --quiet` in .tmp/librarian/cache/source/git/c3b3adb5d1295c5d0e8a9fff5cb92427
[Librarian]     --- No output
[Librarian] Running `/usr/local/git/bin/git fetch origin --quiet --tags` in .tmp/librarian/cache/source/git/c3b3adb5d1295c5d0e8a9fff5cb92427
[Librarian]     --- No output
[Librarian] Running `/usr/local/git/bin/git remote` in .tmp/librarian/cache/source/git/c3b3adb5d1295c5d0e8a9fff5cb92427
[Librarian]     --> origin
[Librarian] Running `/usr/local/git/bin/git branch -r` in .tmp/librarian/cache/source/git/c3b3adb5d1295c5d0e8a9fff5cb92427
[Librarian]     -->   origin/HEAD -> origin/master
[Librarian]     -->   origin/docs_experiment
[Librarian]     -->   origin/feature/master/dans_refactor
[Librarian]     -->   origin/master
[Librarian]     -->   origin/release/quantal_support
[Librarian] Running `/usr/local/git/bin/git rev-parse origin/master^{commit} --quiet` in .tmp/librarian/cache/source/git/c3b3adb5d1295c5d0e8a9fff5cb92427
[Librarian]     --> 3e3de6ee924ea75463e9df4ffdb5712c0e145403
[Librarian] Running `/usr/local/git/bin/git rev-parse HEAD --quiet` in .tmp/librarian/cache/source/git/c3b3adb5d1295c5d0e8a9fff5cb92427
[Librarian]     --> 3e3de6ee924ea75463e9df4ffdb5712c0e145403
[Librarian] Running `/usr/local/git/bin/git rev-parse HEAD --quiet` in .tmp/librarian/cache/source/git/c3b3adb5d1295c5d0e8a9fff5cb92427
[Librarian]     --> 3e3de6ee924ea75463e9df4ffdb5712c0e145403
[Librarian]     Checking apt/1.3.0 <https://github.com/puppetlabs/puppetlabs-apt.git#master>
[Librarian]       Scheduling puppetlabs/stdlib (>= 2.2.1) <http://forge.puppetlabs.com>
[Librarian]       Resolving postgresql (>= 0) <https://github.com/puppetlabs/puppetlabs-postgresql.git#master>
[Librarian]         No known prior constraints
[Librarian]         Checking manifests
[Librarian] Running `/usr/local/git/bin/git reset --hard --quiet` in .tmp/librarian/cache/source/git/c8ab041dfbc932c291264d2099db810f
[Librarian]     --- No output
[Librarian] Running `/usr/local/git/bin/git clean -x -d --force --force` in .tmp/librarian/cache/source/git/c8ab041dfbc932c291264d2099db810f
[Librarian]     --- No output
[Librarian] Running `/usr/local/git/bin/git rev-parse HEAD --quiet` in .tmp/librarian/cache/source/git/c8ab041dfbc932c291264d2099db810f
[Librarian]     --> 6ac2e25821cd6b656979d68a90ebf1bee42c580f
[Librarian] Running `/usr/local/git/bin/git fetch origin --quiet` in .tmp/librarian/cache/source/git/c8ab041dfbc932c291264d2099db810f
[Librarian]     --- No output
[Librarian] Running `/usr/local/git/bin/git fetch origin --quiet --tags` in .tmp/librarian/cache/source/git/c8ab041dfbc932c291264d2099db810f
[Librarian]     --- No output
[Librarian] Running `/usr/local/git/bin/git remote` in .tmp/librarian/cache/source/git/c8ab041dfbc932c291264d2099db810f
[Librarian]     --> origin
[Librarian] Running `/usr/local/git/bin/git branch -r` in .tmp/librarian/cache/source/git/c8ab041dfbc932c291264d2099db810f
[Librarian]     -->   origin/HEAD -> origin/master
[Librarian]     -->   origin/master
[Librarian] Running `/usr/local/git/bin/git rev-parse origin/master^{commit} --quiet` in .tmp/librarian/cache/source/git/c8ab041dfbc932c291264d2099db810f
[Librarian]     --> 6ac2e25821cd6b656979d68a90ebf1bee42c580f
[Librarian] Running `/usr/local/git/bin/git rev-parse HEAD --quiet` in .tmp/librarian/cache/source/git/c8ab041dfbc932c291264d2099db810f
[Librarian]     --> 6ac2e25821cd6b656979d68a90ebf1bee42c580f
[Librarian] Running `/usr/local/git/bin/git rev-parse HEAD --quiet` in .tmp/librarian/cache/source/git/c8ab041dfbc932c291264d2099db810f
[Librarian]     --> 6ac2e25821cd6b656979d68a90ebf1bee42c580f
[Librarian]           Checking postgresql/2.5.0 <https://github.com/puppetlabs/puppetlabs-postgresql.git#master>
[Librarian]             Scheduling puppetlabs/apt (< 2.0.0, >= 1.1.0) <http://forge.puppetlabs.com>
[Librarian]             Scheduling puppetlabs/concat (< 2.0.0, >= 1.0.0) <http://forge.puppetlabs.com>
[Librarian]             Scheduling puppetlabs/firewall (>= 0.0.4) <http://forge.puppetlabs.com>
[Librarian]             Scheduling puppetlabs/stdlib (< 5.0.0, >= 3.2.0) <http://forge.puppetlabs.com>
[Librarian]             Resolving puppetlabs/stdlib (>= 2.2.1) <http://forge.puppetlabs.com>
[Librarian]               No known prior constraints
[Librarian]               Checking manifests
[Librarian]                 Checking puppetlabs/stdlib/4.1.0 <http://forge.puppetlabs.com>
[Librarian]                   Resolving puppetlabs/apt (< 2.0.0, >= 1.1.0) <http://forge.puppetlabs.com>
[Librarian]                     No known prior constraints
[Librarian]                     Checking manifests
[Librarian]                       Checking puppetlabs/apt/1.3.0 <http://forge.puppetlabs.com>
[Librarian]                         Scheduling puppetlabs/stdlib (>= 2.2.1) <>
[Librarian]                         Resolving puppetlabs/concat (< 2.0.0, >= 1.0.0) <http://forge.puppetlabs.com>
[Librarian]                           No known prior constraints
[Librarian]                           Checking manifests
[Librarian]                             Checking puppetlabs/concat/1.0.0-rc1 <http://forge.puppetlabs.com>
[Librarian]                               Resolving puppetlabs/firewall (>= 0.0.4) <http://forge.puppetlabs.com>
[Librarian]                                 No known prior constraints
[Librarian]                                 Checking manifests
[Librarian]                                   Checking puppetlabs/firewall/0.4.2 <http://forge.puppetlabs.com>
[Librarian]                                     Resolving puppetlabs/stdlib (< 5.0.0, >= 3.2.0) <http://forge.puppetlabs.com>
[Librarian]                                       Accords with all prior constraints
[Librarian]                                     Resolving puppetlabs/stdlib (>= 2.2.1) <>
[Librarian]                                       Accords with all prior constraints
[Librarian]                                     Resolved puppetlabs/firewall (>= 0.0.4) <http://forge.puppetlabs.com> at puppetlabs/firewall/0.4.2 <http://forge.puppetlabs.com>
[Librarian]                                 Resolved puppetlabs/firewall (>= 0.0.4) <http://forge.puppetlabs.com>
[Librarian]                               Resolved puppetlabs/concat (< 2.0.0, >= 1.0.0) <http://forge.puppetlabs.com> at puppetlabs/concat/1.0.0-rc1 <http://forge.puppetlabs.com>
[Librarian]                           Resolved puppetlabs/concat (< 2.0.0, >= 1.0.0) <http://forge.puppetlabs.com>
[Librarian]                         Resolved puppetlabs/apt (< 2.0.0, >= 1.1.0) <http://forge.puppetlabs.com> at puppetlabs/apt/1.3.0 <http://forge.puppetlabs.com>
[Librarian]                     Resolved puppetlabs/apt (< 2.0.0, >= 1.1.0) <http://forge.puppetlabs.com>
[Librarian]                   Resolved puppetlabs/stdlib (>= 2.2.1) <http://forge.puppetlabs.com> at puppetlabs/stdlib/4.1.0 <http://forge.puppetlabs.com>
[Librarian]               Resolved puppetlabs/stdlib (>= 2.2.1) <http://forge.puppetlabs.com>
[Librarian]             Resolved postgresql (>= 0) <https://github.com/puppetlabs/puppetlabs-postgresql.git#master> at postgresql/2.5.0 <https://github.com/puppetlabs/puppetlabs-postgresql.git#master>
[Librarian]         Resolved postgresql (>= 0) <https://github.com/puppetlabs/puppetlabs-postgresql.git#master>
[Librarian]       Resolved apt (>= 0) <https://github.com/puppetlabs/puppetlabs-apt.git#master> at apt/1.3.0 <https://github.com/puppetlabs/puppetlabs-apt.git#master>
[Librarian]   Resolved apt (>= 0) <https://github.com/puppetlabs/puppetlabs-apt.git#master>
[Librarian] Bouncing Puppetfile.lock
[Librarian] Pre-Cached Sources:
[Librarian] Post-Cached Sources:
[Librarian]   [:git, "https://github.com/puppetlabs/puppetlabs-apt.git", {}]
[Librarian]   [:git, "https://github.com/puppetlabs/puppetlabs-postgresql.git", {}]
/usr/local/rvm/rubies/ruby-2.0.0-p247/lib/ruby/site_ruby/2.0.0/rubygems/version.rb:191:in `initialize': Malformed version number string Error: (ArgumentError)
    from /usr/local/rvm/rubies/ruby-2.0.0-p247/lib/ruby/site_ruby/2.0.0/rubygems/version.rb:182:in `new'
    from /usr/local/rvm/rubies/ruby-2.0.0-p247/lib/ruby/site_ruby/2.0.0/rubygems/version.rb:182:in `create'
    from /usr/local/rvm/gems/ruby-2.0.0-p247/gems/librarian-puppet-0.9.10/lib/librarian/puppet/source/forge.rb:112:in `check_puppet_module_options'
    from /usr/local/rvm/gems/ruby-2.0.0-p247/gems/librarian-puppet-0.9.10/lib/librarian/puppet/source/forge.rb:91:in `cache_version_unpacked!'
    from /usr/local/rvm/gems/ruby-2.0.0-p247/gems/librarian-puppet-0.9.10/lib/librarian/puppet/source/forge.rb:48:in `install_version!'
    from /usr/local/rvm/gems/ruby-2.0.0-p247/gems/librarian-puppet-0.9.10/lib/librarian/puppet/source/forge.rb:236:in `install!'
    from /usr/local/rvm/gems/ruby-2.0.0-p247/gems/librarian-puppet-0.9.10/vendor/librarian/lib/librarian/manifest.rb:191:in `install!'
    from /usr/local/rvm/gems/ruby-2.0.0-p247/gems/librarian-puppet-0.9.10/vendor/librarian/lib/librarian/action/install.rb:49:in `block in install_manifests'
    from /usr/local/rvm/gems/ruby-2.0.0-p247/gems/librarian-puppet-0.9.10/vendor/librarian/lib/librarian/action/install.rb:48:in `each'
    from /usr/local/rvm/gems/ruby-2.0.0-p247/gems/librarian-puppet-0.9.10/vendor/librarian/lib/librarian/action/install.rb:48:in `install_manifests'
    from /usr/local/rvm/gems/ruby-2.0.0-p247/gems/librarian-puppet-0.9.10/vendor/librarian/lib/librarian/action/install.rb:39:in `perform_installation'
    from /usr/local/rvm/gems/ruby-2.0.0-p247/gems/librarian-puppet-0.9.10/vendor/librarian/lib/librarian/action/install.rb:12:in `run'
    from /usr/local/rvm/gems/ruby-2.0.0-p247/gems/librarian-puppet-0.9.10/vendor/librarian/lib/librarian/cli.rb:157:in `install!'
    from /usr/local/rvm/gems/ruby-2.0.0-p247/gems/librarian-puppet-0.9.10/lib/librarian/puppet/cli.rb:64:in `install'
    from /usr/local/rvm/gems/ruby-2.0.0-p247/gems/thor-0.18.1/lib/thor/command.rb:27:in `run'
    from /usr/local/rvm/gems/ruby-2.0.0-p247/gems/thor-0.18.1/lib/thor/invocation.rb:120:in `invoke_command'
    from /usr/local/rvm/gems/ruby-2.0.0-p247/gems/thor-0.18.1/lib/thor.rb:363:in `dispatch'
    from /usr/local/rvm/gems/ruby-2.0.0-p247/gems/thor-0.18.1/lib/thor/base.rb:439:in `start'
    from /usr/local/rvm/gems/ruby-2.0.0-p247/gems/librarian-puppet-0.9.10/vendor/librarian/lib/librarian/cli.rb:29:in `bin!'
    from /usr/local/rvm/gems/ruby-2.0.0-p247/gems/librarian-puppet-0.9.10/bin/librarian-puppet:9:in `<top (required)>'
    from /usr/local/rvm/gems/ruby-2.0.0-p247/bin/librarian-puppet:23:in `load'
    from /usr/local/rvm/gems/ruby-2.0.0-p247/bin/librarian-puppet:23:in `<main>'
    from /usr/local/rvm/gems/ruby-2.0.0-p247/bin/ruby_executable_hooks:14:in `eval'
    from /usr/local/rvm/gems/ruby-2.0.0-p247/bin/ruby_executable_hooks:14:in `<main>'
```

My Puppetfile:

```
mod 'apt',
     :git => 'https://github.com/puppetlabs/puppetlabs-apt.git'
mod 'postgresql',
     :git => 'https://github.com/puppetlabs/puppetlabs-postgresql.git'
```

It was choking on the forge method call as well. It seems it's non-deterministic what it fails on, as I've changed the modules around a few times and it dies on different things. Not sure why I can't get this to work out of the box...

**Comment by rubo77** [comment]
I had a similar problem "Malformed version number" and it was caused by a `.git` folder that was in one of my folders where there should be only folders named by version numbers. solved it by deleting the .git folder
