### ISSUE TITLE
x does not exist, something went wrong. Try removing it manually

### ISSUE THREAD

**Issue by andyjansson** [rodjek/librarian-puppet#213]
Librarian-puppet fails on first module listed, regardless of which one it is. --verbose output below: 

```
Running librarian-puppet update
[Librarian] Ruby Version: 1.9.3
[Librarian] Ruby Platform: i386-mingw32
[Librarian] Rubygems Version: 1.8.24
[Librarian] Librarian Version: 0.1.2
[Librarian] Librarian Adapter: puppet
[Librarian] Librarian Adapter Version: 1.0.1
[Librarian] Project: C:\ProgramData\PuppetLabs\puppet\etc
[Librarian] Specfile: Puppetfile
[Librarian] Lockfile: Puppetfile.lock
[Librarian] Git: C:/Program Files (x86)/Git/cmd/git.EXE
[Librarian] Git Version: 1.9.2
[Librarian] Git Environment Variables:
[Librarian]   (empty)
[Librarian] Pre-Cached Sources:
[Librarian] Post-Cached Sources:
[Librarian]   [:forge, "http://forge.puppetlabs.com", {}]
[Librarian]   [:git, "git://github.com/ferventcoder/puppet-chocolatey.git", {:ref=>"all_the_things"}]
[Librarian] Resolving joshcooper/powershell (>= 0) <http://forge.puppetlabs.com>
[Librarian]   Checking manifests
[Librarian] Querying Forge API for module joshcooper/powershell: http://forge.puppetlabs.com/api/v1/releases.json?module=joshcooper/powershell
[Librarian]   Module joshcooper/powershell found versions: 0.0.6, 0.0.5, 0.0.4,0.0.2, 0.0.1
[Librarian]     Checking joshcooper/powershell/0.0.6 <http://forge.puppetlabs.com>
[Librarian]       Resolving puppetlabs/registry (>= 0) <http://forge.puppetlabs.com>
[Librarian]         Checking manifests
[Librarian] Querying Forge API for module puppetlabs/registry: http://forge.puppetlabs.com/api/v1/releases.json?module=puppetlabs/registry
[Librarian]   Module puppetlabs/registry found versions: 1.0.0, 0.1.2, 0.1.1, 0.1.0
[Librarian]           Checking puppetlabs/registry/1.0.0 <http://forge.puppetlabs.com>
[Librarian]             Resolving rismoney/chocolatey (>= 0) <git://github.com/ferventcoder/puppet-chocolatey.git#all_the_things>
[Librarian]               Checking manifests
[Librarian]     --- No output
[Librarian]     --- No output
[Librarian]     --- No output
[Librarian]     --- No output
[Librarian]     --> origin
[Librarian]     -->   origin/HEAD -> origin/master
[Librarian]     -->   origin/add_source
[Librarian]     -->   origin/all_the_things
[Librarian]     -->   origin/fix_explicit_vers
[Librarian]     -->   origin/master
[Librarian]     -->   origin/use_list_instead
[Librarian]     --> d16fff5f97aa0c4f39d7fb92d7e4e00853e89004
[Librarian]     --> d16fff5f97aa0c4f39d7fb92d7e4e00853e89004
[Librarian]                 Checking rismoney/chocolatey/0.0.1 <git://github.com/ferventcoder/puppet-chocolatey.git#all_the_things>
[Librarian]                   Resolving puppetlabs/dism (>= 0) <http://forge.puppetlabs.com>
[Librarian]                     Checking manifests
[Librarian] Querying Forge API for module puppetlabs/dism: http://forge.puppetlabs.com/api/v1/releases.json?module=puppetlabs/dism
[Librarian]   Module puppetlabs/dism found versions: 0.1.0
[Librarian]                       Checking puppetlabs/dism/0.1.0 <http://forge.puppetlabs.com>
[Librarian]                         Resolving puppetlabs/reboot (>= 0) <http://forge.puppetlabs.com>
[Librarian]                           Checking manifests
[Librarian] Querying Forge API for module puppetlabs/reboot: http://forge.puppetlabs.com/api/v1/releases.json?module=puppetlabs/reboot
[Librarian]   Module puppetlabs/reboot found versions: 0.1.5, 0.1.4, 0.1.2, 0.1.1, 0.1.0
[Librarian]                             Checking puppetlabs/reboot/0.1.5 <http://forge.puppetlabs.com>
[Librarian]                               Resolving puppetlabs/stdlib (>= 2.3.0) <(no source specified)>
[Librarian]                                 Checking manifests
[Librarian] Querying Forge API for module puppetlabs/stdlib: http://forge.puppetlabs.com/api/v1/releases.json?module=puppetlabs/stdlib
[Librarian]   Module puppetlabs/stdlib found versions: 4.1.0, 3.2.1, 3.2.0, 3.1.1, 3.1.0, 3.0.1, 3.0.0, 2.6.0, 2.5.1, 2.5.0, 2.4.0, 2.3.3, 2.3.2, 2.3.1, 2.3.0,2.2.1, 2.2.0, 2.1.3, 2.0.0, 1.1.0, 1.0.0, 0.1.7, 0.1.6, 0.1.5, 0.1.4, 0.1.3, 0.1.2, 0.1.1
[Librarian]                                   Checking puppetlabs/stdlib/4.1.0 <http://forge.puppetlabs.com>
[Librarian]                                     Resolved puppetlabs/stdlib (>= 2.3.0) <(no source specified)> at puppetlabs/stdlib/4.1.0 <http://forge.puppetlabs.com>
[Librarian]                                 Resolved puppetlabs/stdlib (>= 2.3.0) <(no source specified)>
[Librarian]                               Resolved puppetlabs/reboot (>= 0) <http://forge.puppetlabs.com> at puppetlabs/reboot/0.1.5 <http://forge.puppetlabs.com>
[Librarian]                           Resolved puppetlabs/reboot (>= 0) <http://forge.puppetlabs.com>
[Librarian]                         Resolved puppetlabs/dism (>= 0) <http://forge.puppetlabs.com> at puppetlabs/dism/0.1.0 <http://forge.puppetlabs.com>
[Librarian]                     Resolved puppetlabs/dism (>= 0) <http://forge.puppetlabs.com>
[Librarian]                   Resolved rismoney/chocolatey (>= 0) <git://github.com/ferventcoder/puppet-chocolatey.git#all_the_things> at rismoney/chocolatey/0.0.1 <git://github.com/ferventcoder/puppet-chocolatey.git#all_the_things>
[Librarian]               Resolved rismoney/chocolatey (>= 0) <git://github.com/ferventcoder/puppet-chocolatey.git#all_the_things>
[Librarian]             Resolved puppetlabs/registry (>= 0) <http://forge.puppetlabs.com> at puppetlabs/registry/1.0.0 <http://forge.puppetlabs.com>
[Librarian]         Resolved puppetlabs/registry (>= 0) <http://forge.puppetlabs.com>
[Librarian]       Resolved joshcooper/powershell (>= 0) <http://forge.puppetlabs.com> at joshcooper/powershell/0.0.6 <http://forge.puppetlabs.com>
[Librarian]   Resolved joshcooper/powershell (>= 0) <http://forge.puppetlabs.com>
[Librarian] Bouncing Puppetfile.lock
[Librarian] Pre-Cached Sources:
[Librarian] Post-Cached Sources:
[Librarian]   [:forge, "http://forge.puppetlabs.com", {}]
[Librarian]   [:git, "git://github.com/ferventcoder/puppet-chocolatey.git", {:ref=>"all_the_things"}]
C:\ProgramData\PuppetLabs\puppet\etc/.tmp/librarian/cache/source/puppet/forge/3792e516e3ff92a0ef9f5e827f8e76eb/joshcooper/powershell/version/0303f93637e61e28843862449f225607/powershell does not exist, something went wrong. Try removing it manually
C:/Program Files (x86)/Puppet Labs/Puppet/sys/ruby/lib/ruby/gems/1.9.1/gems/librarian-puppet-1.0.1/lib/librarian/puppet/source/forge.rb:67:in `install_version!'
C:/Program Files (x86)/Puppet Labs/Puppet/sys/ruby/lib/ruby/gems/1.9.1/gems/librarian-puppet-1.0.1/lib/librarian/puppet/source/forge.rb:292:in `install!'
C:/Program Files (x86)/Puppet Labs/Puppet/sys/ruby/lib/ruby/gems/1.9.1/gems/librarian-0.1.2/lib/librarian/manifest.rb:101:in `install!'
C:/Program Files (x86)/Puppet Labs/Puppet/sys/ruby/lib/ruby/gems/1.9.1/gems/librarian-0.1.2/lib/librarian/action/install.rb:49:in `block in install_manifests'
C:/Program Files (x86)/Puppet Labs/Puppet/sys/ruby/lib/ruby/gems/1.9.1/gems/librarian-0.1.2/lib/librarian/action/install.rb:48:in `each'
C:/Program Files (x86)/Puppet Labs/Puppet/sys/ruby/lib/ruby/gems/1.9.1/gems/librarian-0.1.2/lib/librarian/action/install.rb:48:in `install_manifests'
C:/Program Files (x86)/Puppet Labs/Puppet/sys/ruby/lib/ruby/gems/1.9.1/gems/librarian-0.1.2/lib/librarian/action/install.rb:39:in `perform_installation'
C:/Program Files (x86)/Puppet Labs/Puppet/sys/ruby/lib/ruby/gems/1.9.1/gems/librarian-0.1.2/lib/librarian/action/install.rb:12:in `run'
C:/Program Files (x86)/Puppet Labs/Puppet/sys/ruby/lib/ruby/gems/1.9.1/gems/librarian-0.1.2/lib/librarian/cli.rb:165:in `install!'
C:/Program Files (x86)/Puppet Labs/Puppet/sys/ruby/lib/ruby/gems/1.9.1/gems/librarian-0.1.2/lib/librarian/cli.rb:117:in `update'
C:/Program Files (x86)/Puppet Labs/Puppet/sys/ruby/lib/ruby/gems/1.9.1/gems/thor-0.19.1/lib/thor/command.rb:27:in `run'
C:/Program Files (x86)/Puppet Labs/Puppet/sys/ruby/lib/ruby/gems/1.9.1/gems/thor-0.19.1/lib/thor/invocation.rb:126:in `invoke_command'
C:/Program Files (x86)/Puppet Labs/Puppet/sys/ruby/lib/ruby/gems/1.9.1/gems/thor-0.19.1/lib/thor.rb:359:in `dispatch'
C:/Program Files (x86)/Puppet Labs/Puppet/sys/ruby/lib/ruby/gems/1.9.1/gems/thor-0.19.1/lib/thor/base.rb:440:in `start'
C:/Program Files (x86)/Puppet Labs/Puppet/sys/ruby/lib/ruby/gems/1.9.1/gems/librarian-0.1.2/lib/librarian/cli.rb:26:in `block (2 levels) in bin!'
C:/Program Files (x86)/Puppet Labs/Puppet/sys/ruby/lib/ruby/gems/1.9.1/gems/librarian-0.1.2/lib/librarian/cli.rb:31:in `returning_status'
C:/Program Files (x86)/Puppet Labs/Puppet/sys/ruby/lib/ruby/gems/1.9.1/gems/librarian-0.1.2/lib/librarian/cli.rb:26:in `block in bin!'
C:/Program Files (x86)/Puppet Labs/Puppet/sys/ruby/lib/ruby/gems/1.9.1/gems/librarian-0.1.2/lib/librarian/cli.rb:47:in `with_environment'
C:/Program Files (x86)/Puppet Labs/Puppet/sys/ruby/lib/ruby/gems/1.9.1/gems/librarian-0.1.2/lib/librarian/cli.rb:26:in `bin!'
C:/Program Files (x86)/Puppet Labs/Puppet/sys/ruby/lib/ruby/gems/1.9.1/gems/librarian-puppet-1.0.1/bin/librarian-puppet:7:in `<top (required)>'
C:/Program Files (x86)/Puppet Labs/Puppet/sys/ruby/bin/librarian-puppet:23:in `load'
C:/Program Files (x86)/Puppet Labs/Puppet/sys/ruby/bin/librarian-puppet:23:in `<main>'
```

Puppet is running inside of a Windows 7 Pro guest system managed by Vagrant 1.6.x.

**Comment by Breeze773** [comment]
I'm still seeing this problem on -v 2.0.1
I'm sorry to bring this up since it seems like there was a lot of back and forth on this one in this thread with the thought that the latest version of librarian-puppet would have fixed this.  
I first came across this with v 1.4.1.
I then rolled back to v 1.3.2 hoping that maybe that fixed bug regressed.

Here's my debugging output.  Let me know if you'd like me to try any different versions of anything.  I tried multiple versions of the librarian-puppet gem, as I stated in combination for ruby version 1.9.3, 2.0 and 2.1.5

### RUBY VERSION
`ruby 2.1.5p273 (2014-11-13 revision 48405) [x64-mingw32]`

### GEMS
activemodel (4.2.0)
activesupport (4.2.0)
bigdecimal (1.2.4)
builder (3.2.2)
faraday (0.9.1)
her (0.7.3)
highline (1.6.21)
i18n (0.7.0)
io-console (0.4.2)
json (1.8.1)
librarian (0.1.2)
librarian-puppet (2.0.1)
minitest (5.5.1, 4.7.5)
multi_json (1.10.1)
multipart-post (2.0.0)
psych (2.0.5)
puppet_forge (1.0.4)
rake (10.1.0)
rdoc (4.1.0)
rsync (1.0.9)
test-unit (2.1.5.0)
thor (0.19.1)
thread_safe (0.3.4)
tzinfo (1.2.2)

### librarian-puppet install --verbose
```
[Librarian] Ruby Version: 2.1.5
[Librarian] Ruby Platform: x64-mingw32
[Librarian] Rubygems Version: 2.2.2
[Librarian] Librarian Version: 0.1.2
[Librarian] Librarian Adapter: puppet
[Librarian] Librarian Adapter Version: 2.0.1
[Librarian] Project: c:/tmp/Deployment/puppet
[Librarian] Specfile: Puppetfile
[Librarian] Lockfile: Puppetfile.lock
[Librarian] Git: C:/Program Files (x86)/Git/cmd/git.EXE
[Librarian] Git Version: 1.9.4
[Librarian] Git Environment Variables:
[Librarian]   (empty)
[Librarian] Pre-Cached Sources:
[Librarian]   [:forge, "https://forgeapi.puppetlabs.com", {}]
[Librarian] Post-Cached Sources:
[Librarian]   [:forge, "https://forgeapi.puppetlabs.com", {}]
[Librarian] The specfile is unchanged: nothing to do.
[Librarian] Install: dependencies resolved
[Librarian] Pre-Cached Sources:
[Librarian] Post-Cached Sources:
[Librarian]   [:forge, "https://forgeapi.puppetlabs.com", {}]
[Librarian] Installing badgerious-windows_env/2.2.1 <https://forgeapi.puppetlabs.com>
c:\temp/librarian/cache/source/puppet/forge/forgeapi_puppetlabs_com/badgerious-windows_env/2.2.1/windows_env does not exist, something went wrong. Try removing it manually
C:/Ruby21-x64/lib/ruby/gems/2.1.0/gems/librarian-puppet-2.0.1/lib/librarian/puppet/source/forge/repo.rb:65:in `install_version!'
C:/Ruby21-x64/lib/ruby/gems/2.1.0/gems/librarian-puppet-2.0.1/lib/librarian/puppet/source/forge.rb:114:in `install!'
C:/Ruby21-x64/lib/ruby/gems/2.1.0/gems/librarian-0.1.2/lib/librarian/manifest.rb:101:in `install!'
C:/Ruby21-x64/lib/ruby/gems/2.1.0/gems/librarian-0.1.2/lib/librarian/action/install.rb:49:in `block in install_manifests'
C:/Ruby21-x64/lib/ruby/gems/2.1.0/gems/librarian-0.1.2/lib/librarian/action/install.rb:48:in `each'
C:/Ruby21-x64/lib/ruby/gems/2.1.0/gems/librarian-0.1.2/lib/librarian/action/install.rb:48:in `install_manifests'
C:/Ruby21-x64/lib/ruby/gems/2.1.0/gems/librarian-0.1.2/lib/librarian/action/install.rb:39:in `perform_installation'
C:/Ruby21-x64/lib/ruby/gems/2.1.0/gems/librarian-0.1.2/lib/librarian/action/install.rb:12:in `run'
C:/Ruby21-x64/lib/ruby/gems/2.1.0/gems/librarian-puppet-2.0.1/lib/librarian/puppet/cli.rb:94:in `install!'
C:/Ruby21-x64/lib/ruby/gems/2.1.0/gems/librarian-puppet-2.0.1/lib/librarian/puppet/cli.rb:69:in `install'
C:/Ruby21-x64/lib/ruby/gems/2.1.0/gems/thor-0.19.1/lib/thor/command.rb:27:in `run'
C:/Ruby21-x64/lib/ruby/gems/2.1.0/gems/thor-0.19.1/lib/thor/invocation.rb:126:in `invoke_command'
C:/Ruby21-x64/lib/ruby/gems/2.1.0/gems/thor-0.19.1/lib/thor.rb:359:in `dispatch'
C:/Ruby21-x64/lib/ruby/gems/2.1.0/gems/thor-0.19.1/lib/thor/base.rb:440:in `start'
C:/Ruby21-x64/lib/ruby/gems/2.1.0/gems/librarian-0.1.2/lib/librarian/cli.rb:26:in `block (2 levels) in bin!'
C:/Ruby21-x64/lib/ruby/gems/2.1.0/gems/librarian-0.1.2/lib/librarian/cli.rb:31:in `returning_status'
C:/Ruby21-x64/lib/ruby/gems/2.1.0/gems/librarian-0.1.2/lib/librarian/cli.rb:26:in `block in bin!'
C:/Ruby21-x64/lib/ruby/gems/2.1.0/gems/librarian-0.1.2/lib/librarian/cli.rb:47:in `with_environment'
C:/Ruby21-x64/lib/ruby/gems/2.1.0/gems/librarian-0.1.2/lib/librarian/cli.rb:26:in `bin!'
C:/Ruby21-x64/lib/ruby/gems/2.1.0/gems/librarian-puppet-2.0.1/bin/librarian-puppet:7:in `<top (required)>'
C:/Ruby21-x64/bin/librarian-puppet:23:in `load'
C:/Ruby21-x64/bin/librarian-puppet:23:in `<main>'
```

**Comment by Breeze773** [comment]
One added piece of info from my previous post.  I have a Team City project running `librarian-puppet install` in one of my build steps.  For whatever reason, when TC executes that command it works fine.  Could it be a permissions thing?  I did run the above as admin, btw.

**Comment by carlossg** [comment]
Seems the problem only happens in windows. If you could run the test suite (with `rake`) and post the output then I could take a look.
