### ISSUE TITLE
'Cannot bounce Puppetfile.lock!' error when Forge modules contain duplicated dependencies

### ISSUE THREAD

**Issue by daks** [rodjek/librarian-puppet#223]
Hello,

I use librarian-puppet 1.0.2 on Debian Wheezy 7.5. Puppet version is 3.6.1-1puppetlabs1 (from Puppetlabs apt repository).

My working Puppetfile is

```
forge "http://forge.puppetlabs.com"

mod "opentable/windowsfeature"
mod "garethr/kibana"
mod "akumria/nullmailer", "1.3.2"
mod "elasticsearch/logstash", "0.4.3"
mod "puppetlabs/apt"
mod "daks/wget",
  :git => "https://github.com/daks/puppet-wget.git"
mod "elasticsearch/elasticsearch", "0.3.0"
mod "dwerder/graphite"
```

librarian-puppet install do the job normally

If I add 

```
mod "pdxcat/collectd"
```

I got this error

```
Cannot bounce Puppetfile.lock!
```

Running with --verbose give this

```
[Librarian] Ruby Version: 1.9.3
[Librarian] Ruby Platform: x86_64-linux
[Librarian] Rubygems Version: 1.8.23
[Librarian] Librarian Version: 0.1.2
[Librarian] Librarian Adapter: puppet
[Librarian] Librarian Adapter Version: 1.0.2
[Librarian] Project: /etc/puppet/environments/experimental
[Librarian] Specfile: Puppetfile
[Librarian] Lockfile: Puppetfile.lock
[Librarian] Git: /usr/bin/git
[Librarian] Git Version: 1.7.10.4
[Librarian] Git Environment Variables:
[Librarian]   (empty)
[Librarian] Pre-Cached Sources:
[Librarian]   [:forge, "http://forge.puppetlabs.com", {}]
[Librarian]   [:git, "https://github.com/daks/puppet-wget.git", {}]
[Librarian] Post-Cached Sources:
[Librarian]   [:forge, "http://forge.puppetlabs.com", {}]
[Librarian]   [:git, "https://github.com/daks/puppet-wget.git", {}]
[Librarian] Analyzing spec and lock:
[Librarian]   Removed:
[Librarian]   ExplicitRemoved:
[Librarian]   Added:
[Librarian]     pdxcat/collectd
[Librarian]   NonMatchingAdded:
[Librarian]     pdxcat/collectd
[Librarian]   Changed:
[Librarian]   DeepKeep:
[Librarian]     akumria/nullmailer
[Librarian]     daks/wget
[Librarian]     dwerder/graphite
[Librarian]     elasticsearch/elasticsearch
[Librarian]     elasticsearch/logstash
[Librarian]     garethr/kibana
[Librarian]     opentable/windowsfeature
[Librarian]     puppetlabs/apt
[Librarian]   ShallowStrip:
[Librarian] Resolving pdxcat/collectd (>= 0) <http://forge.puppetlabs.com>
[Librarian]   Checking manifests
[Librarian] Querying Forge API for module pdxcat/collectd: http://forge.puppetlabs.com/api/v1/releases.json?module=pdxcat/collectd
[Librarian]   Module pdxcat/collectd found versions: 2.1.0, 2.0.1, 1.1.0, 1.0.2, 1.0.1, 1.0.0, 0.1.0, 0.0.5, 0.0.4, 0.0.3, 0.0.2, 0.0.1
[Librarian]     Checking pdxcat/collectd/2.1.0 <http://forge.puppetlabs.com>
[Librarian]       Resolved pdxcat/collectd (>= 0) <http://forge.puppetlabs.com> at pdxcat/collectd/2.1.0 <http://forge.puppetlabs.com>
[Librarian]   Resolved pdxcat/collectd (>= 0) <http://forge.puppetlabs.com>
[Librarian] Bouncing Puppetfile.lock
[Librarian] lockfile_text:
FORGE
  remote: http://forge.puppetlabs.com
  specs:
    akumria/nullmailer (1.3.2)
      puppetlabs/stdlib (>= 2.3.1)
    dwerder/graphite (5.3.2)
      puppetlabs/stdlib (>= 3.2.0)
    elasticsearch/elasticsearch (0.3.0)
      puppetlabs/stdlib (>= 3.2.0)
    elasticsearch/logstash (0.4.3)
      ispavailability/file_concat (>= 0.1.0)
      puppetlabs/stdlib (>= 3.2.0)
    garethr/kibana (0.2.0)
      ploperations/bundler (>= 0.0.0)
      puppetlabs/git (>= 0.0.0)
      puppetlabs/ruby (>= 0.0.0)
      puppetlabs/stdlib (>= 0.0.0)
      puppetlabs/vcsrepo (>= 0.0.0)
    ispavailability/file_concat (0.1.0)
    joshcooper/powershell (0.0.6)
    opentable/windowsfeature (0.1.2)
      joshcooper/powershell (>= 0.0.6)
      puppetlabs/stdlib (>= 3.0.0)
    pdxcat/collectd (2.1.0)
      puppetlabs/stdlib (>= 3.0.0)
      puppetlabs/stdlib (>= 3.0.0)
    ploperations/bundler (1.0.0)
    puppetlabs/apt (1.4.2)
      puppetlabs/stdlib (>= 2.2.1)
    puppetlabs/git (0.0.3)
    puppetlabs/ruby (0.1.0)
    puppetlabs/stdlib (4.2.1)
    puppetlabs/vcsrepo (0.2.0)

GIT
  remote: https://github.com/daks/puppet-wget.git
  ref: master
  sha: 4d77be8de5154261e801512331633b9990b417af
  specs:
    daks/wget (0.0.1)

DEPENDENCIES
  akumria/nullmailer (= 1.3.2)
  daks/wget (>= 0)
  dwerder/graphite (>= 0)
  elasticsearch/elasticsearch (= 0.3.0)
  elasticsearch/logstash (= 0.4.3)
  garethr/kibana (>= 0)
  opentable/windowsfeature (>= 0)
  pdxcat/collectd (>= 0)
  puppetlabs/apt (>= 0)

[Librarian] bounced_lockfile_text:
FORGE
  remote: http://forge.puppetlabs.com
  specs:
    akumria/nullmailer (1.3.2)
      puppetlabs/stdlib (>= 2.3.1)
    dwerder/graphite (5.3.2)
      puppetlabs/stdlib (>= 3.2.0)
    elasticsearch/elasticsearch (0.3.0)
      puppetlabs/stdlib (>= 3.2.0)
    elasticsearch/logstash (0.4.3)
      ispavailability/file_concat (>= 0.1.0)
      puppetlabs/stdlib (>= 3.2.0)
    garethr/kibana (0.2.0)
      ploperations/bundler (>= 0.0.0)
      puppetlabs/git (>= 0.0.0)
      puppetlabs/ruby (>= 0.0.0)
      puppetlabs/stdlib (>= 0.0.0)
      puppetlabs/vcsrepo (>= 0.0.0)
    ispavailability/file_concat (0.1.0)
    joshcooper/powershell (0.0.6)
    opentable/windowsfeature (0.1.2)
      joshcooper/powershell (>= 0.0.6)
      puppetlabs/stdlib (>= 3.0.0)
    pdxcat/collectd (2.1.0)
      puppetlabs/stdlib (>= 3.0.0)
    ploperations/bundler (1.0.0)
    puppetlabs/apt (1.4.2)
      puppetlabs/stdlib (>= 2.2.1)
    puppetlabs/git (0.0.3)
    puppetlabs/ruby (0.1.0)
    puppetlabs/stdlib (4.2.1)
    puppetlabs/vcsrepo (0.2.0)

GIT
  remote: https://github.com/daks/puppet-wget.git
  ref: master
  sha: 4d77be8de5154261e801512331633b9990b417af
  specs:
    daks/wget (0.0.1)

DEPENDENCIES
  akumria/nullmailer (= 1.3.2)
  daks/wget (>= 0)
  dwerder/graphite (>= 0)
  elasticsearch/elasticsearch (= 0.3.0)
  elasticsearch/logstash (= 0.4.3)
  garethr/kibana (>= 0)
  opentable/windowsfeature (>= 0)
  pdxcat/collectd (>= 0)
  puppetlabs/apt (>= 0)

Cannot bounce Puppetfile.lock!
/var/lib/gems/1.9.1/gems/librarian-0.1.2/lib/librarian/action/persist_resolution_mixin.rb:20:in `persist_resolution'
/var/lib/gems/1.9.1/gems/librarian-0.1.2/lib/librarian/action/resolve.rb:27:in `run'
/var/lib/gems/1.9.1/gems/librarian-0.1.2/lib/librarian/cli.rb:169:in `resolve!'
/var/lib/gems/1.9.1/gems/librarian-puppet-1.0.2/lib/librarian/puppet/cli.rb:69:in `install'
/var/lib/gems/1.9.1/gems/thor-0.18.1/lib/thor/command.rb:27:in `run'
/var/lib/gems/1.9.1/gems/thor-0.18.1/lib/thor/invocation.rb:120:in `invoke_command'
/var/lib/gems/1.9.1/gems/thor-0.18.1/lib/thor.rb:363:in `dispatch'
/var/lib/gems/1.9.1/gems/thor-0.18.1/lib/thor/base.rb:439:in `start'
/var/lib/gems/1.9.1/gems/librarian-0.1.2/lib/librarian/cli.rb:26:in `block (2 levels) in bin!'
/var/lib/gems/1.9.1/gems/librarian-0.1.2/lib/librarian/cli.rb:31:in `returning_status'
/var/lib/gems/1.9.1/gems/librarian-0.1.2/lib/librarian/cli.rb:26:in `block in bin!'
/var/lib/gems/1.9.1/gems/librarian-0.1.2/lib/librarian/cli.rb:47:in `with_environment'
/var/lib/gems/1.9.1/gems/librarian-0.1.2/lib/librarian/cli.rb:26:in `bin!'
/var/lib/gems/1.9.1/gems/librarian-puppet-1.0.2/bin/librarian-puppet:7:in `<top (required)>'
/usr/local/bin/librarian-puppet:23:in `load'
/usr/local/bin/librarian-puppet:23:in `<main>'
```

I don't understand the error message and how to solve it

**Comment by robinbowes** [comment]
I've just run into the same issue (well, the same error message).
