### ISSUE TITLE
--no-use-v1-api option does not work on 1.4.1

### ISSUE THREAD

**Issue by Breeze773** [rodjek/librarian-puppet#279]
I am trying to get librarian-puppet working on a windows system.  I am having problems where it seems to try to hit v1 of the forge api regardless of using the --no-use-v1-api option.  

Here's some helpful info for troubleshooting.  Please let me know if you need anything else.
Ruby version
`ruby 1.9.3p551 (2014-11-13) [i386-mingw32]`
Gems
gem list
*** LOCAL GEMS ***
bigdecimal (1.1.0)
facter (2.3.0 x86-mingw32)
ffi (1.9.6 x86-mingw32, 1.9.3 x86-mingw32)
hiera (1.3.4)
highline (1.6.21)
i18n (0.7.0)
io-console (0.3)
json (1.5.5)
json_pure (1.8.2)
librarian (0.1.2)
**librarian-puppet (1.4.1)**
minitar (0.5.4)
minitest (2.5.1)
**puppet (3.7.3 x86-mingw32)**
rake (0.9.2.2)
rdoc (3.9.5)
rsync (1.0.9)
thor (0.19.1)
win32-dir (0.4.9)
win32-eventlog (0.6.2)
win32-process (0.7.4)
win32-security (0.2.5)
win32-service (0.8.6)
win32console (1.3.2 x86-mingw32)

Failure
**librarian-puppet install --verbose --no-use-v1-api**
[Librarian] Ruby Version: 1.9.3
[Librarian] Ruby Platform: i386-mingw32
[Librarian] Rubygems Version: 1.8.29
[Librarian] Librarian Version: 0.1.2
[Librarian] Librarian Adapter: puppet
[Librarian] Librarian Adapter Version: 1.4.1
[Librarian] Project: c:/work/p1s/Deployment/puppet
[Librarian] Specfile: Puppetfile
[Librarian] Lockfile: Puppetfile.lock
[Librarian] Git: C:/Program Files (x86)/Git/cmd/git.EXE
[Librarian] Git Version: 1.9.4
[Librarian] Git Environment Variables:
[Librarian]   (empty)
[Librarian] Pre-Cached Sources:
[Librarian] Post-Cached Sources:
[Librarian]   [:forge, "https://forgeapi.puppetlabs.com", {}]
[Librarian] Resolving counsyl-windows (= 0.9.3) <https://forgeapi.puppetlabs.com>
[Librarian]   Checking manifests
[Librarian] Querying Forge API for module counsyl-windows: **https://forgeapi.puppetlabs.com/api/v1/releases.json?module=counsyl/windows**
Unable to find module 'counsyl-windows' on https://forgeapi.puppetlabs.com
C:/Ruby193/lib/ruby/gems/1.9.1/gems/librarian-puppet-1.4.1/lib/librarian/puppet/source/forge/repo_v1.rb:76:in `api_data'
C:/Ruby193/lib/ruby/gems/1.9.1/gems/librarian-puppet-1.4.1/lib/librarian/puppet/source/forge/repo_v1.rb:22:in `get_versions'
C:/Ruby193/lib/ruby/gems/1.9.1/gems/librarian-puppet-1.4.1/lib/librarian/puppet/source/forge/repo.rb:15:in `versions'
C:/Ruby193/lib/ruby/gems/1.9.1/gems/librarian-puppet-1.4.1/lib/librarian/puppet/source/forge/repo.rb:42:in `manifests'
C:/Ruby193/lib/ruby/gems/1.9.1/gems/librarian-puppet-1.4.1/lib/librarian/puppet/source/forge.rb:152:in `manifests'
C:/Ruby193/lib/ruby/gems/1.9.1/gems/librarian-0.1.2/lib/librarian/dependency.rb:117:in `cache_manifests!'
C:/Ruby193/lib/ruby/gems/1.9.1/gems/librarian-0.1.2/lib/librarian/dependency.rb:113:in `manifests'
C:/Ruby193/lib/ruby/gems/1.9.1/gems/librarian-0.1.2/lib/librarian/resolver/implementation.rb:152:in `block in resolving_dependency_map_find_manifests'
C:/Ruby193/lib/ruby/gems/1.9.1/gems/librarian-0.1.2/lib/librarian/resolver/implementation.rb:165:in `block (2 levels) in scope_resolving_dependency'
C:/Ruby193/lib/ruby/gems/1.9.1/gems/librarian-0.1.2/lib/librarian/resolver/implementation.rb:179:in `block in scope_checking_manifests'
C:/Ruby193/lib/ruby/gems/1.9.1/gems/librarian-0.1.2/lib/librarian/resolver/implementation.rb:223:in `scope'
C:/Ruby193/lib/ruby/gems/1.9.1/gems/librarian-0.1.2/lib/librarian/resolver/implementation.rb:178:in `scope_checking_manifests'
C:/Ruby193/lib/ruby/gems/1.9.1/gems/librarian-0.1.2/lib/librarian/resolver/implementation.rb:164:in `block in scope_resolving_dependency'
C:/Ruby193/lib/ruby/gems/1.9.1/gems/librarian-0.1.2/lib/librarian/resolver/implementation.rb:223:in `scope'
C:/Ruby193/lib/ruby/gems/1.9.1/gems/librarian-0.1.2/lib/librarian/resolver/implementation.rb:163:in `scope_resolving_dependency'
C:/Ruby193/lib/ruby/gems/1.9.1/gems/librarian-0.1.2/lib/librarian/resolver/implementation.rb:151:in `resolving_dependency_map_find_manifests'
C:/Ruby193/lib/ruby/gems/1.9.1/gems/librarian-0.1.2/lib/librarian/resolver/implementation.rb:62:in `recursive_resolve'
C:/Ruby193/lib/ruby/gems/1.9.1/gems/librarian-0.1.2/lib/librarian/resolver/implementation.rb:50:in `resolve'
C:/Ruby193/lib/ruby/gems/1.9.1/gems/librarian-0.1.2/lib/librarian/resolver.rb:23:in `resolve'
C:/Ruby193/lib/ruby/gems/1.9.1/gems/librarian-0.1.2/lib/librarian/action/resolve.rb:26:in `run'
C:/Ruby193/lib/ruby/gems/1.9.1/gems/librarian-0.1.2/lib/librarian/cli.rb:169:in `resolve!'
C:/Ruby193/lib/ruby/gems/1.9.1/gems/librarian-puppet-1.4.1/lib/librarian/puppet/cli.rb:67:in `install'
C:/Ruby193/lib/ruby/gems/1.9.1/gems/thor-0.19.1/lib/thor/command.rb:27:in `run'
C:/Ruby193/lib/ruby/gems/1.9.1/gems/thor-0.19.1/lib/thor/invocation.rb:126:in `invoke_command'
C:/Ruby193/lib/ruby/gems/1.9.1/gems/thor-0.19.1/lib/thor.rb:359:in `dispatch'
C:/Ruby193/lib/ruby/gems/1.9.1/gems/thor-0.19.1/lib/thor/base.rb:440:in `start'
C:/Ruby193/lib/ruby/gems/1.9.1/gems/librarian-0.1.2/lib/librarian/cli.rb:26:in `block (2 levels) in bin!'
C:/Ruby193/lib/ruby/gems/1.9.1/gems/librarian-0.1.2/lib/librarian/cli.rb:31:in `returning_status'
C:/Ruby193/lib/ruby/gems/1.9.1/gems/librarian-0.1.2/lib/librarian/cli.rb:26:in `block in bin!'
C:/Ruby193/lib/ruby/gems/1.9.1/gems/librarian-0.1.2/lib/librarian/cli.rb:47:in `with_environment'
C:/Ruby193/lib/ruby/gems/1.9.1/gems/librarian-0.1.2/lib/librarian/cli.rb:26:in `bin!'
C:/Ruby193/lib/ruby/gems/1.9.1/gems/librarian-puppet-1.4.1/bin/librarian-puppet:7:in `<top (required)>'
C:/Ruby193/bin/librarian-puppet:23:in `load'
C:/Ruby193/bin/librarian-puppet:23:in `<main>'

**Comment by Breeze773** [comment]
Sorry.  I might have posted a bit too soon.  I found more info that I should use 
`forge "https://forge.puppetlabs.com"`
in my Puppetfile
I was using 
`forge "https://forgeapi.puppetlabs.com"`
No on to other rubygem dependency issues, that may or may not be related to this gem
