### ISSUE TITLE
Following Modulefile causes "Expected DEPENDENCIES topic!" error

### ISSUE THREAD

**Issue by amosshapira** [rodjek/librarian-puppet#28]
A module which uses the following file causes librarian-puppet to bomb out with the following stack trace:
Modulefile:
```
name    'infrastructure-sssd'
version '0.0.1'
source '...'
author 'infrastructure'
license '...'
summary 'Installs & configure the SSSD authentication stack.'
description '...'
project_page '...'

## Add dependencies, if any:
# dependency 'username/name', '>= 1.2.0'
```
Error (last lines):
```
[Librarian] Running `/usr/bin/git rev-parse HEAD --quiet` in .tmp/librarian/cache/source/git/87ef4d15f8b5ed59d08fa1757f4dd854
[Librarian]     --- No output
[Librarian]     Checking sssd/0.0.1 <git@bitbucket.org:infrastructure/puppet-module-sssd.git#master>
[Librarian]       Resolved sssd (>= 0) <git@bitbucket.org:infrastructure/puppet-module-sssd.git#master> at sssd/0.0.1 <git@bitbucket.org:infrastructure/puppet-module-sssd.git#master>
[Librarian]   Resolved sssd (>= 0) <git@bitbucket.org:infrastructure/puppet-module-sssd.git#master>
[Librarian] Bouncing Puppetfile.lock
/usr/lib/ruby/gems/1.8/gems/librarian-puppet-0.9.3/lib/librarian/puppet/lockfile/parser.rb:41:in `parse': Expected DEPENDENCIES topic! (StandardError)
	from /usr/lib/ruby/gems/1.8/gems/librarian-puppet-0.9.3/vendor/librarian/lib/librarian/lockfile.rb:21:in `load'
	from /usr/lib/ruby/gems/1.8/gems/librarian-puppet-0.9.3/vendor/librarian/lib/librarian/action/resolve.rb:31:in `run'
	from /usr/lib/ruby/gems/1.8/gems/librarian-puppet-0.9.3/vendor/librarian/lib/librarian/cli.rb:161:in `resolve!'
	from /usr/lib/ruby/gems/1.8/gems/librarian-puppet-0.9.3/lib/librarian/puppet/cli.rb:59:in `install'
	from /usr/lib/ruby/gems/1.8/gems/thor-0.16.0/lib/thor/task.rb:27:in `send'
	from /usr/lib/ruby/gems/1.8/gems/thor-0.16.0/lib/thor/task.rb:27:in `run'
	from /usr/lib/ruby/gems/1.8/gems/thor-0.16.0/lib/thor/invocation.rb:120:in `invoke_task'
	from /usr/lib/ruby/gems/1.8/gems/thor-0.16.0/lib/thor.rb:275:in `dispatch'
	from /usr/lib/ruby/gems/1.8/gems/thor-0.16.0/lib/thor/base.rb:425:in `start'
	from /usr/lib/ruby/gems/1.8/gems/librarian-puppet-0.9.3/vendor/librarian/lib/librarian/cli.rb:29:in `bin!'
	from /usr/lib/ruby/gems/1.8/gems/librarian-puppet-0.9.3/bin/librarian-puppet:9
	from /usr/bin/librarian-puppet:19:in `load'
	from /usr/bin/librarian-puppet:19
```
Puppetfile:
```
mod 'sssd',
  :git => 'git@bitbucket.org:infrastructure/puppet-module-sssd.git'
```

**Comment by carlossg** [comment]
No longer causes librarian to fail
