### ISSUE TITLE
Cannot bounce Puppetfile.lock!

### ISSUE THREAD

**Issue by AndreTheHunter** [rodjek/librarian-puppet#282]
When I try to run `librarian-puppet install` I get a `Cannot bounce Puppetfile.lock!` error. Running on OSX 10.10.2 with Puppet 3.7.4

Puppetfile
```
mod 'concrete/basic_server',
	:git => "ssh://git@src01.office.concreteplatform.net/puppet/basic_server.git"

mod 'concrete/motd',
	:git => "ssh://git@src01.office.concreteplatform.net/puppet/motd.git"

mod 'concrete/shibboleth',
	:git => "ssh://git@src01.office.concreteplatform.net/puppet/shibboleth.git"
```

librarian-puppet install --verbose
```
[Librarian] Ruby Version: 2.2.0
[Librarian] Ruby Platform: x86_64-darwin14
[Librarian] Rubygems Version: 2.4.5
[Librarian] Librarian Version: 0.1.2
[Librarian] Librarian Adapter: puppet
[Librarian] Librarian Adapter Version: 2.0.1
[Librarian] Project: /Users/andre.dejager/Coding/Concrete/sso
[Librarian] Specfile: Puppetfile
[Librarian] Lockfile: Puppetfile.lock
[Librarian] Git: /usr/local/bin/git
[Librarian] Git Version: 2.3.0
[Librarian] Git Environment Variables:
[Librarian]   (empty)
[Librarian] Pre-Cached Sources:
[Librarian] Post-Cached Sources:
[Librarian]   [:git, "ssh://git@src01.office.concreteplatform.net/puppet/basic_server.git", {}]
[Librarian]   [:git, "ssh://git@src01.office.concreteplatform.net/puppet/motd.git", {}]
[Librarian]   [:git, "ssh://git@src01.office.concreteplatform.net/puppet/shibboleth.git", {}]
[Librarian] Resolving concrete-basic_server (>= 0) <ssh://git@src01.office.concreteplatform.net/puppet/basic_server.git#master>
[Librarian]   Checking manifests
[Librarian]     --- No output
[Librarian]     --- No output
[Librarian]     --- No output
[Librarian]     --- No output
[Librarian]     --> origin
[Librarian]     -->   origin/HEAD -> origin/master
[Librarian]     -->   origin/master
[Librarian]     --> 9813d434added0792b6b0f4baee841baf46c64ea
[Librarian]     --> 9813d434added0792b6b0f4baee841baf46c64ea
[Librarian]     Checking concrete-basic_server/0.1.0 <ssh://git@src01.office.concreteplatform.net/puppet/basic_server.git#master>
[Librarian]       Resolving concrete-motd (>= 0) <ssh://git@src01.office.concreteplatform.net/puppet/motd.git#master>
[Librarian]         Checking manifests
[Librarian]     --- No output
[Librarian]     --- No output
[Librarian]     --- No output
[Librarian]     --- No output
[Librarian]     --> origin
[Librarian]     -->   origin/HEAD -> origin/master
[Librarian]     -->   origin/master
[Librarian]     --> a51d16cb9df272b5a4687317763174e8a13a89bd
[Librarian]     --> a51d16cb9df272b5a4687317763174e8a13a89bd
[Librarian]           Checking concrete-motd/1.0.0 <ssh://git@src01.office.concreteplatform.net/puppet/motd.git#master>
[Librarian]             Resolving concrete-shibboleth (>= 0) <ssh://git@src01.office.concreteplatform.net/puppet/shibboleth.git#master>
[Librarian]               Checking manifests
[Librarian]     --- No output
[Librarian]     --- No output
[Librarian]     --- No output
[Librarian]     --- No output
[Librarian]     --> origin
[Librarian]     -->   origin/HEAD -> origin/master
[Librarian]     -->   origin/master
[Librarian]     --> f86d0a73394e190e3438a5fb8d9443240b52f395
[Librarian]     --> f86d0a73394e190e3438a5fb8d9443240b52f395
[Librarian]                 Checking concrete-shibboleth/0.1.0 <ssh://git@src01.office.concreteplatform.net/puppet/shibboleth.git#master>
[Librarian] Pre-Cached Sources:
[Librarian] Post-Cached Sources:
[Librarian]   [:git, "ssh://git@src01.office.concreteplatform.net/puppet/basic_server.git", {}]
[Librarian]   [:git, "ssh://git@src01.office.concreteplatform.net/puppet/motd.git", {}]
[Librarian]                   Resolving puppetlabs-apt (>= 1.7.0) <https://forgeapi.puppetlabs.com>
[Librarian]                     Checking manifests
[Librarian]   Module puppetlabs-apt found versions: 1.7.0, 1.6.0, 1.5.2, 1.5.1, 1.5.0, 1.4.2, 1.4.1, 1.4.0, 1.3.0, 1.2.0, 1.1.1, 1.1.0, 1.0.1, 1.0.0, 0.0.4, 0.0.3, 0.0.2, 0.0.1
[Librarian]                       Checking puppetlabs-apt/1.7.0 <https://forgeapi.puppetlabs.com>
[Librarian]                         Resolving puppetlabs-stdlib (< 5.0.0, >= 4.2.0) <https://forgeapi.puppetlabs.com>
[Librarian]                           Checking manifests
[Librarian]   Module puppetlabs-stdlib found versions: 4.5.1, 4.5.0, 4.4.0, 4.3.2, 4.3.0, 4.2.2, 4.2.1, 4.2.0, 4.1.0, 3.2.2, 3.2.1, 3.2.0, 3.1.1, 3.1.0, 3.0.1, 3.0.0, 2.6.0, 2.5.1, 2.5.0, 2.4.0, 2.3.3, 2.3.2, 2.3.1, 2.3.0, 2.2.1, 2.2.0, 2.1.3, 2.0.0, 1.1.0, 1.0.0, 0.1.7, 0.1.6, 0.1.5, 0.1.4, 0.1.3, 0.1.2, 0.1.1
[Librarian]                             Checking puppetlabs-stdlib/4.5.1 <https://forgeapi.puppetlabs.com>
[Librarian]                               Resolving puppetlabs-concat (>= 1.1.0) <https://forgeapi.puppetlabs.com>
[Librarian]                                 Checking manifests
[Librarian]   Module puppetlabs-concat found versions: 1.1.2, 1.1.1, 1.1.0, 1.1.0-rc1, 1.0.4, 1.0.3, 1.0.2, 1.0.1, 1.0.0, 1.0.0-rc1
[Librarian]                                   Checking puppetlabs-concat/1.1.2 <https://forgeapi.puppetlabs.com>
[Librarian]                                     Resolved puppetlabs-concat (>= 1.1.0) <https://forgeapi.puppetlabs.com> at puppetlabs-concat/1.1.2 <https://forgeapi.puppetlabs.com>
[Librarian]                                 Resolved puppetlabs-concat (>= 1.1.0) <https://forgeapi.puppetlabs.com>
[Librarian]                               Resolved puppetlabs-stdlib (< 5.0.0, >= 4.2.0) <https://forgeapi.puppetlabs.com> at puppetlabs-stdlib/4.5.1 <https://forgeapi.puppetlabs.com>
[Librarian]                           Resolved puppetlabs-stdlib (< 5.0.0, >= 4.2.0) <https://forgeapi.puppetlabs.com>
[Librarian]                         Resolved puppetlabs-apt (>= 1.7.0) <https://forgeapi.puppetlabs.com> at puppetlabs-apt/1.7.0 <https://forgeapi.puppetlabs.com>
[Librarian]                     Resolved puppetlabs-apt (>= 1.7.0) <https://forgeapi.puppetlabs.com>
[Librarian]                   Resolved concrete-shibboleth (>= 0) <ssh://git@src01.office.concreteplatform.net/puppet/shibboleth.git#master> at concrete-shibboleth/0.1.0 <ssh://git@src01.office.concreteplatform.net/puppet/shibboleth.git#master>
[Librarian]               Resolved concrete-shibboleth (>= 0) <ssh://git@src01.office.concreteplatform.net/puppet/shibboleth.git#master>
[Librarian]             Resolved concrete-motd (>= 0) <ssh://git@src01.office.concreteplatform.net/puppet/motd.git#master> at concrete-motd/1.0.0 <ssh://git@src01.office.concreteplatform.net/puppet/motd.git#master>
[Librarian]         Resolved concrete-motd (>= 0) <ssh://git@src01.office.concreteplatform.net/puppet/motd.git#master>
[Librarian]       Resolved concrete-basic_server (>= 0) <ssh://git@src01.office.concreteplatform.net/puppet/basic_server.git#master> at concrete-basic_server/0.1.0 <ssh://git@src01.office.concreteplatform.net/puppet/basic_server.git#master>
[Librarian]   Resolved concrete-basic_server (>= 0) <ssh://git@src01.office.concreteplatform.net/puppet/basic_server.git#master>
[Librarian] Bouncing Puppetfile.lock
[Librarian] lockfile_text: 
FORGE
  remote: https://forgeapi.puppetlabs.com
  specs:
    puppetlabs-apt (1.7.0)
      puppetlabs-stdlib (>= 2.2.1)
    puppetlabs-concat (1.1.2)
      puppetlabs-stdlib (< 5.0.0, >= 3.2.0)
    puppetlabs-stdlib (4.5.1)

GIT
  remote: ssh://git@src01.office.concreteplatform.net/puppet/basic_server.git
  ref: master
  sha: 9813d434added0792b6b0f4baee841baf46c64ea
  specs:
    concrete-basic_server (0.1.0)
      concrete-motd (>= 1.0.0)
      puppetlabs-apt (>= 1.7.0)
      puppetlabs-stdlib (< 5.0.0, >= 4.2.0)

GIT
  remote: ssh://git@src01.office.concreteplatform.net/puppet/motd.git
  ref: master
  sha: a51d16cb9df272b5a4687317763174e8a13a89bd
  specs:
    concrete-motd (1.0.0)
      puppetlabs-concat (>= 1.1.0)
      puppetlabs-stdlib (< 5.0.0, >= 4.2.0)

GIT
  remote: ssh://git@src01.office.concreteplatform.net/puppet/shibboleth.git
  ref: master
  sha: f86d0a73394e190e3438a5fb8d9443240b52f395
  specs:
    concrete-shibboleth (0.1.0)
      concrete-basic_server (>= 0)
      concrete-basic_server (< 1.0.0, >= 0.1.0)
      concrete-motd (>= 0)
      puppetlabs-apt (< 2.0.0, >= 1.7.0)
      puppetlabs-stdlib (< 5.0.0, >= 4.2.0)

DEPENDENCIES
  concrete-basic_server (>= 0)
  concrete-motd (>= 0)
  concrete-shibboleth (>= 0)

[Librarian] bounced_lockfile_text: 
FORGE
  remote: https://forgeapi.puppetlabs.com
  specs:
    puppetlabs-apt (1.7.0)
      puppetlabs-stdlib (>= 2.2.1)
    puppetlabs-concat (1.1.2)
      puppetlabs-stdlib (< 5.0.0, >= 3.2.0)
    puppetlabs-stdlib (4.5.1)

GIT
  remote: ssh://git@src01.office.concreteplatform.net/puppet/basic_server.git
  ref: master
  sha: 9813d434added0792b6b0f4baee841baf46c64ea
  specs:
    concrete-basic_server (0.1.0)
      concrete-motd (>= 1.0.0)
      puppetlabs-apt (>= 1.7.0)
      puppetlabs-stdlib (< 5.0.0, >= 4.2.0)

GIT
  remote: ssh://git@src01.office.concreteplatform.net/puppet/motd.git
  ref: master
  sha: a51d16cb9df272b5a4687317763174e8a13a89bd
  specs:
    concrete-motd (1.0.0)
      puppetlabs-concat (>= 1.1.0)
      puppetlabs-stdlib (< 5.0.0, >= 4.2.0)

GIT
  remote: ssh://git@src01.office.concreteplatform.net/puppet/shibboleth.git
  ref: master
  sha: f86d0a73394e190e3438a5fb8d9443240b52f395
  specs:
    concrete-shibboleth (0.1.0)
      concrete-basic_server (< 1.0.0, >= 0.1.0)
      concrete-motd (>= 0)
      puppetlabs-apt (< 2.0.0, >= 1.7.0)
      puppetlabs-stdlib (< 5.0.0, >= 4.2.0)

DEPENDENCIES
  concrete-basic_server (>= 0)
  concrete-motd (>= 0)
  concrete-shibboleth (>= 0)

Cannot bounce Puppetfile.lock!
/usr/local/lib/ruby/gems/2.2.0/gems/librarian-0.1.2/lib/librarian/action/persist_resolution_mixin.rb:20:in `persist_resolution'
/usr/local/lib/ruby/gems/2.2.0/gems/librarian-0.1.2/lib/librarian/action/resolve.rb:27:in `run'
/usr/local/lib/ruby/gems/2.2.0/gems/librarian-0.1.2/lib/librarian/cli.rb:169:in `resolve!'
/usr/local/lib/ruby/gems/2.2.0/gems/librarian-puppet-2.0.1/lib/librarian/puppet/cli.rb:67:in `install'
/usr/local/lib/ruby/gems/2.2.0/gems/thor-0.19.1/lib/thor/command.rb:27:in `run'
/usr/local/lib/ruby/gems/2.2.0/gems/thor-0.19.1/lib/thor/invocation.rb:126:in `invoke_command'
/usr/local/lib/ruby/gems/2.2.0/gems/thor-0.19.1/lib/thor.rb:359:in `dispatch'
/usr/local/lib/ruby/gems/2.2.0/gems/thor-0.19.1/lib/thor/base.rb:440:in `start'
/usr/local/lib/ruby/gems/2.2.0/gems/librarian-0.1.2/lib/librarian/cli.rb:26:in `block (2 levels) in bin!'
/usr/local/lib/ruby/gems/2.2.0/gems/librarian-0.1.2/lib/librarian/cli.rb:31:in `returning_status'
/usr/local/lib/ruby/gems/2.2.0/gems/librarian-0.1.2/lib/librarian/cli.rb:26:in `block in bin!'
/usr/local/lib/ruby/gems/2.2.0/gems/librarian-0.1.2/lib/librarian/cli.rb:47:in `with_environment'
/usr/local/lib/ruby/gems/2.2.0/gems/librarian-0.1.2/lib/librarian/cli.rb:26:in `bin!'
/usr/local/lib/ruby/gems/2.2.0/gems/librarian-puppet-2.0.1/bin/librarian-puppet:7:in `<top (required)>'
/usr/local/bin/librarian-puppet:23:in `load'
/usr/local/bin/librarian-puppet:23:in `<main>'
```

**Comment by carlossg** [comment]
one of your modules has a duplicated dependency

```
GIT
  remote: ssh://git@src01.office.concreteplatform.net/puppet/shibboleth.git
  ref: master
  sha: f86d0a73394e190e3438a5fb8d9443240b52f395
  specs:
    concrete-shibboleth (0.1.0)
      concrete-basic_server (>= 0)
      concrete-basic_server (< 1.0.0, >= 0.1.0)
```

**Comment by AndreTheHunter** [comment]
Thank you.
The duplication was caused by having the dependency define in my metadata.json as well as the Puppetfile. Moving everything to use Puppetfile now...
