### ISSUE TITLE
undefined method `dump' for Psych:Module

### ISSUE THREAD

**Issue by AndreTheHunter** [rodjek/librarian-puppet#283]
When I run librarian-puppet install and various other commands, I get the following error (with --verbose)

```
[Librarian] Ruby Version: 2.2.0
[Librarian] Ruby Platform: x86_64-darwin14
[Librarian] Rubygems Version: 2.4.5
[Librarian] Librarian Version: 0.1.2
[Librarian] Librarian Adapter: puppet
[Librarian] Librarian Adapter Version: 2.0.1
[Librarian] Project: /Users/andre.dejager/Coding/Concrete-Puppet/motd
[Librarian] Specfile: Puppetfile
[Librarian] Lockfile: Puppetfile.lock
[Librarian] Git: /usr/local/bin/git
[Librarian] Git Version: 2.3.0
[Librarian] Git Environment Variables:
[Librarian]   (empty)
/usr/local/lib/ruby/gems/2.2.0/gems/librarian-0.1.2/lib/librarian/config/file_source.rb:27:in `load': undefined method `load_file' for Psych:Module (NoMethodError)
	from /usr/local/lib/ruby/gems/2.2.0/gems/librarian-0.1.2/lib/librarian/config/source.rb:60:in `load!'
	from /usr/local/lib/ruby/gems/2.2.0/gems/librarian-0.1.2/lib/librarian/config/source.rb:40:in `[]='
	from /usr/local/lib/ruby/gems/2.2.0/gems/librarian-puppet-2.0.1/lib/librarian/puppet/cli.rb:54:in `install'
	from /usr/local/lib/ruby/gems/2.2.0/gems/thor-0.19.1/lib/thor/command.rb:27:in `run'
	from /usr/local/lib/ruby/gems/2.2.0/gems/thor-0.19.1/lib/thor/invocation.rb:126:in `invoke_command'
	from /usr/local/lib/ruby/gems/2.2.0/gems/thor-0.19.1/lib/thor.rb:359:in `dispatch'
	from /usr/local/lib/ruby/gems/2.2.0/gems/thor-0.19.1/lib/thor/base.rb:440:in `start'
	from /usr/local/lib/ruby/gems/2.2.0/gems/librarian-0.1.2/lib/librarian/cli.rb:26:in `block (2 levels) in bin!'
	from /usr/local/lib/ruby/gems/2.2.0/gems/librarian-0.1.2/lib/librarian/cli.rb:31:in `returning_status'
	from /usr/local/lib/ruby/gems/2.2.0/gems/librarian-0.1.2/lib/librarian/cli.rb:26:in `block in bin!'
	from /usr/local/lib/ruby/gems/2.2.0/gems/librarian-0.1.2/lib/librarian/cli.rb:47:in `with_environment'
	from /usr/local/lib/ruby/gems/2.2.0/gems/librarian-0.1.2/lib/librarian/cli.rb:26:in `bin!'
	from /usr/local/lib/ruby/gems/2.2.0/gems/librarian-puppet-2.0.1/bin/librarian-puppet:7:in `<top (required)>'
	from /usr/local/bin/librarian-puppet:23:in `load'
	from /usr/local/bin/librarian-puppet:23:in `<main>'
```

**Comment by carlossg** [comment]
What puppetfile, puppetfile.lock, modulefile and metadata.json are you using?

**Comment by AndreTheHunter** [comment]
Puppetfile.lock would not generate. The only command that seemed to work was --version

I think this error is related to the ruby version. I uninstalled my homebrew installed version of ruby and reverted to the OS X version 2.0.0p481. Then after `sudo gem install librarian-puppet`, it works

**Comment by carlossg** [comment]
I looks to me that some gem was not correctly installed

**Comment by habitullence** [comment]
Same problem, any solution?
