### ISSUE TITLE
certificate verify failed

### ISSUE THREAD

**Issue by sbelenky** [rodjek/librarian-puppet#319]
`Puppetfile ` content:

```
forge "https://forgeapi.puppetlabs.com"
mod 'mjanser-vagrant'
```

`Puppetfile.lock` content:

```
FORGE
  remote: https://forgeapi.puppetlabs.com
  specs:
    puppetlabs-stdlib (4.8.0)

DEPENDENCIES
  puppetlabs-stdlib (>= 0)
```

Version of ruby: `ruby 2.0.0p195 (2013-05-14) [x64-mingw32]`
Version of librarian-puppet: `2.2.1`
Version of puppet: `3.8.2`
Operating System: Windows 7

Verbose output of librarian-puppet:

```
DL is deprecated, please use Fiddle
[Librarian] Ruby Version: 2.0.0
[Librarian] Ruby Platform: x64-mingw32
[Librarian] Rubygems Version: 2.0.2
[Librarian] Librarian Version: 0.6.3
[Librarian] Librarian Adapter: puppet
[Librarian] Librarian Adapter Version: 2.2.1
[Librarian] Project: C:/Users/Slava/virtualization/puppet-test
[Librarian] Specfile: Puppetfile
[Librarian] Lockfile: Puppetfile.lock
[Librarian] Git: C:/Program Files (x86)/Git/cmd/git.EXE
[Librarian] Git Version: 1.9.5
[Librarian] Git Environment Variables:
[Librarian]   (empty)
[Librarian] Pre-Cached Sources:
[Librarian]   [:forge, "https://forgeapi.puppetlabs.com", {}]
[Librarian] Post-Cached Sources:
[Librarian]   [:forge, "https://forgeapi.puppetlabs.com", {}]
[Librarian] Analyzing spec and lock:
[Librarian]   Removed:
[Librarian]     puppetlabs-stdlib
[Librarian]   ExplicitRemoved:
[Librarian]   Added:
[Librarian]     mjanser-vagrant
[Librarian]   NonMatchingAdded:
[Librarian]     mjanser-vagrant
[Librarian]   Changed:
[Librarian]   DeepKeep:
[Librarian]   ShallowStrip:
[Librarian] Resolving mjanser-vagrant (>= 0) <https://forgeapi.puppetlabs.com>
[Librarian]   Checking manifests
C:/Ruby200-x64/lib/ruby/2.0.0/net/http.rb:918:in `connect': SSL_connect returned=1 errno=0 state=SSLv3 read server certificate B: certificate verify failed (Faraday::SSLError)
	from C:/Ruby200-x64/lib/ruby/2.0.0/net/http.rb:918:in `block in connect'
	from C:/Ruby200-x64/lib/ruby/2.0.0/timeout.rb:52:in `timeout'
	from C:/Ruby200-x64/lib/ruby/2.0.0/net/http.rb:918:in `connect'
	from C:/Ruby200-x64/lib/ruby/2.0.0/net/http.rb:862:in `do_start'
	from C:/Ruby200-x64/lib/ruby/2.0.0/net/http.rb:851:in `start'
	from C:/Ruby200-x64/lib/ruby/2.0.0/net/http.rb:1367:in `request'
	from C:/Ruby200-x64/lib/ruby/2.0.0/net/http.rb:1126:in `get'
	from C:/Ruby200-x64/lib/ruby/gems/2.0.0/gems/faraday-0.9.1/lib/faraday/adapter/net_http.rb:80:in `perform_request'
	from C:/Ruby200-x64/lib/ruby/gems/2.0.0/gems/faraday-0.9.1/lib/faraday/adapter/net_http.rb:40:in `block in call'
	from C:/Ruby200-x64/lib/ruby/gems/2.0.0/gems/faraday-0.9.1/lib/faraday/adapter/net_http.rb:87:in `with_net_http_connection'
	from C:/Ruby200-x64/lib/ruby/gems/2.0.0/gems/faraday-0.9.1/lib/faraday/adapter/net_http.rb:32:in `call'
	from C:/Ruby200-x64/lib/ruby/gems/2.0.0/gems/faraday-0.9.1/lib/faraday/response.rb:8:in `call'
	from C:/Ruby200-x64/lib/ruby/gems/2.0.0/gems/faraday-0.9.1/lib/faraday/rack_builder.rb:139:in `build_response'
	from C:/Ruby200-x64/lib/ruby/gems/2.0.0/gems/faraday-0.9.1/lib/faraday/connection.rb:377:in `run_request'
	from C:/Ruby200-x64/lib/ruby/gems/2.0.0/gems/faraday-0.9.1/lib/faraday/connection.rb:140:in `get'
	from C:/Ruby200-x64/lib/ruby/gems/2.0.0/gems/her-0.6.8/lib/her/api.rb:88:in `request'
	from C:/Ruby200-x64/lib/ruby/gems/2.0.0/gems/her-0.6.8/lib/her/model/http.rb:52:in `request'
	from C:/Ruby200-x64/lib/ruby/gems/2.0.0/gems/puppet_forge-1.0.5/lib/puppet_forge/v3/base.rb:59:in `request'
	from C:/Ruby200-x64/lib/ruby/gems/2.0.0/gems/her-0.6.8/lib/her/model/relation.rb:95:in `block in find'
	from C:/Ruby200-x64/lib/ruby/gems/2.0.0/gems/her-0.6.8/lib/her/model/relation.rb:88:in `map'
	from C:/Ruby200-x64/lib/ruby/gems/2.0.0/gems/her-0.6.8/lib/her/model/relation.rb:88:in `find'
	from C:/Ruby200-x64/lib/ruby/gems/2.0.0/gems/her-0.6.8/lib/her/model/orm.rb:127:in `find'
	from C:/Ruby200-x64/lib/ruby/gems/2.0.0/gems/librarian-puppet-2.2.1/lib/librarian/puppet/source/forge/repo_v3.rb:43:in `get_module'
	from C:/Ruby200-x64/lib/ruby/gems/2.0.0/gems/librarian-puppet-2.2.1/lib/librarian/puppet/source/forge/repo_v3.rb:19:in `get_versions'
	from C:/Ruby200-x64/lib/ruby/gems/2.0.0/gems/librarian-puppet-2.2.1/lib/librarian/puppet/source/forge/repo.rb:15:in `versions'
	from C:/Ruby200-x64/lib/ruby/gems/2.0.0/gems/librarian-puppet-2.2.1/lib/librarian/puppet/source/forge/repo.rb:42:in `manifests'
	from C:/Ruby200-x64/lib/ruby/gems/2.0.0/gems/librarian-puppet-2.2.1/lib/librarian/puppet/source/forge.rb:152:in `manifests'
	from C:/Ruby200-x64/lib/ruby/gems/2.0.0/gems/librarianp-0.6.3/lib/librarian/dependency.rb:155:in `cache_manifests!'
	from C:/Ruby200-x64/lib/ruby/gems/2.0.0/gems/librarianp-0.6.3/lib/librarian/dependency.rb:151:in `manifests'
	from C:/Ruby200-x64/lib/ruby/gems/2.0.0/gems/librarianp-0.6.3/lib/librarian/resolver/implementation.rb:159:in `block in resolving_dependency_map_find_manifests'
	from C:/Ruby200-x64/lib/ruby/gems/2.0.0/gems/librarianp-0.6.3/lib/librarian/resolver/implementation.rb:172:in `block (2 levels) in scope_resolving_dependency'
	from C:/Ruby200-x64/lib/ruby/gems/2.0.0/gems/librarianp-0.6.3/lib/librarian/resolver/implementation.rb:186:in `block in scope_checking_manifests'
	from C:/Ruby200-x64/lib/ruby/gems/2.0.0/gems/librarianp-0.6.3/lib/librarian/resolver/implementation.rb:230:in `scope'
	from C:/Ruby200-x64/lib/ruby/gems/2.0.0/gems/librarianp-0.6.3/lib/librarian/resolver/implementation.rb:185:in `scope_checking_manifests'
	from C:/Ruby200-x64/lib/ruby/gems/2.0.0/gems/librarianp-0.6.3/lib/librarian/resolver/implementation.rb:171:in `block in scope_resolving_dependency'
	from C:/Ruby200-x64/lib/ruby/gems/2.0.0/gems/librarianp-0.6.3/lib/librarian/resolver/implementation.rb:230:in `scope'
	from C:/Ruby200-x64/lib/ruby/gems/2.0.0/gems/librarianp-0.6.3/lib/librarian/resolver/implementation.rb:170:in `scope_resolving_dependency'
	from C:/Ruby200-x64/lib/ruby/gems/2.0.0/gems/librarianp-0.6.3/lib/librarian/resolver/implementation.rb:158:in `resolving_dependency_map_find_manifests'
	from C:/Ruby200-x64/lib/ruby/gems/2.0.0/gems/librarianp-0.6.3/lib/librarian/resolver/implementation.rb:65:in `do_resolve'
	from C:/Ruby200-x64/lib/ruby/gems/2.0.0/gems/librarianp-0.6.3/lib/librarian/resolver/implementation.rb:50:in `resolve'
	from C:/Ruby200-x64/lib/ruby/gems/2.0.0/gems/librarianp-0.6.3/lib/librarian/resolver.rb:23:in `resolve'
	from C:/Ruby200-x64/lib/ruby/gems/2.0.0/gems/librarianp-0.6.3/lib/librarian/action/resolve.rb:31:in `run'
	from C:/Ruby200-x64/lib/ruby/gems/2.0.0/gems/librarian-puppet-2.2.1/lib/librarian/puppet/action/resolve.rb:10:in `run'
	from C:/Ruby200-x64/lib/ruby/gems/2.0.0/gems/librarian-puppet-2.2.1/lib/librarian/puppet/cli.rb:104:in `resolve!'
	from C:/Ruby200-x64/lib/ruby/gems/2.0.0/gems/librarian-puppet-2.2.1/lib/librarian/puppet/cli.rb:68:in `install'
	from C:/Ruby200-x64/lib/ruby/gems/2.0.0/gems/thor-0.19.1/lib/thor/command.rb:27:in `run'
	from C:/Ruby200-x64/lib/ruby/gems/2.0.0/gems/thor-0.19.1/lib/thor/invocation.rb:126:in `invoke_command'
	from C:/Ruby200-x64/lib/ruby/gems/2.0.0/gems/thor-0.19.1/lib/thor.rb:359:in `dispatch'
	from C:/Ruby200-x64/lib/ruby/gems/2.0.0/gems/thor-0.19.1/lib/thor/base.rb:440:in `start'
	from C:/Ruby200-x64/lib/ruby/gems/2.0.0/gems/librarianp-0.6.3/lib/librarian/cli.rb:26:in `block (2 levels) in bin!'
	from C:/Ruby200-x64/lib/ruby/gems/2.0.0/gems/librarianp-0.6.3/lib/librarian/cli.rb:31:in `returning_status'
	from C:/Ruby200-x64/lib/ruby/gems/2.0.0/gems/librarianp-0.6.3/lib/librarian/cli.rb:26:in `block in bin!'
	from C:/Ruby200-x64/lib/ruby/gems/2.0.0/gems/librarianp-0.6.3/lib/librarian/cli.rb:47:in `with_environment'
	from C:/Ruby200-x64/lib/ruby/gems/2.0.0/gems/librarianp-0.6.3/lib/librarian/cli.rb:26:in `bin!'
	from C:/Ruby200-x64/lib/ruby/gems/2.0.0/gems/librarian-puppet-2.2.1/bin/librarian-puppet:7:in `<top (required)>'
	from C:/Ruby200-x64/bin/librarian-puppet:23:in `load'
	from C:/Ruby200-x64/bin/librarian-puppet:23:in `<main>'
```

**Comment by sbelenky** [comment]
This turned out to be a Ruby SSL problem solution to which is here: http://stackoverflow.com/questions/10775640/omniauth-facebook-error-faradayerrorconnectionfailed
