### ISSUE TITLE
Librarian-puppet 2.2.1 insists on using v1-api

### ISSUE THREAD

**Issue by alecswan** [rodjek/librarian-puppet#338]
Hi there,

I was able to use "librarian-puppet install --verbose --no-use-v1-api" command to install puppet modules. After that I started playing with different switches and ran the command with --use-v1-api. Now, whatever I do librarian-puppet insists on using v1 api by accessing the v1 URL at https://maven.us.example.com:8443/nexus/service/siesta/puppetforge/puppetModules/api/v1/releases.json

What can I do to really force librarian puppet not to use v1 api?

```
> librarian-puppet clean
> librarian-puppet config use-v1-api 0 --global
> librarian-puppet config
destructive: false
path: modules
use-v1-api: 0
> librarian-puppet install --verbose --no-use-v1-api --path modules
[Librarian] Ruby Version: 1.9.3
[Librarian] Ruby Platform: x86_64-darwin14.3.0
[Librarian] Rubygems Version: 2.4.8
[Librarian] Librarian Version: 0.6.3
[Librarian] Librarian Adapter: puppet
[Librarian] Librarian Adapter Version: 2.2.1
[Librarian] Project: /Users/alec/Documents/dev/example/puppet-ng/role_anomalytics_notification
[Librarian] Specfile: Puppetfile
[Librarian] Lockfile: Puppetfile.lock
[Librarian] Git: /usr/local/bin/git
[Librarian] Git Version: 2.5.0
[Librarian] Git Environment Variables:
[Librarian]   (empty)
[Librarian] Pre-Cached Sources:
[Librarian] Post-Cached Sources:
[Librarian]   [:forge, "https://maven.us.example.com:8443/nexus/service/siesta/puppetforge/puppetModules", {}]
[Librarian] Resolving pp-profile_dnsclient (= 2) <https://maven.us.example.com:8443/nexus/service/siesta/puppetforge/puppetModules>
[Librarian]   Checking manifests
[Librarian] Querying Forge API for module pp-profile_dnsclient: https://maven.us.example.com:8443/nexus/service/siesta/puppetforge/puppetModules/api/v1/releases.json?module=pp/profile_dnsclient
Unable to find module 'pp-profile_dnsclient' on https://maven.us.example.com:8443/nexus/service/siesta/puppetforge/puppetModules
/Users/alec/.rvm/gems/ruby-1.9.3-p551@global/gems/librarian-puppet-2.2.1/lib/librarian/puppet/source/forge/repo_v1.rb:55:in `api_data'
/Users/alec/.rvm/gems/ruby-1.9.3-p551@global/gems/librarian-puppet-2.2.1/lib/librarian/puppet/source/forge/repo_v1.rb:22:in `get_versions'
/Users/alec/.rvm/gems/ruby-1.9.3-p551@global/gems/librarian-puppet-2.2.1/lib/librarian/puppet/source/forge/repo.rb:15:in `versions'
/Users/alec/.rvm/gems/ruby-1.9.3-p551@global/gems/librarian-puppet-2.2.1/lib/librarian/puppet/source/forge/repo.rb:42:in `manifests'
/Users/alec/.rvm/gems/ruby-1.9.3-p551@global/gems/librarian-puppet-2.2.1/lib/librarian/puppet/source/forge.rb:152:in `manifests'
/Users/alec/.rvm/gems/ruby-1.9.3-p551@global/gems/librarianp-0.6.3/lib/librarian/dependency.rb:155:in `cache_manifests!'
/Users/alec/.rvm/gems/ruby-1.9.3-p551@global/gems/librarianp-0.6.3/lib/librarian/dependency.rb:151:in `manifests'
/Users/alec/.rvm/gems/ruby-1.9.3-p551@global/gems/librarianp-0.6.3/lib/librarian/resolver/implementation.rb:159:in `block in resolving_dependency_map_find_manifests'
/Users/alec/.rvm/gems/ruby-1.9.3-p551@global/gems/librarianp-0.6.3/lib/librarian/resolver/implementation.rb:172:in `block (2 levels) in scope_resolving_dependency'
/Users/alec/.rvm/gems/ruby-1.9.3-p551@global/gems/librarianp-0.6.3/lib/librarian/resolver/implementation.rb:186:in `block in scope_checking_manifests'
/Users/alec/.rvm/gems/ruby-1.9.3-p551@global/gems/librarianp-0.6.3/lib/librarian/resolver/implementation.rb:230:in `scope'
/Users/alec/.rvm/gems/ruby-1.9.3-p551@global/gems/librarianp-0.6.3/lib/librarian/resolver/implementation.rb:185:in `scope_checking_manifests'
/Users/alec/.rvm/gems/ruby-1.9.3-p551@global/gems/librarianp-0.6.3/lib/librarian/resolver/implementation.rb:171:in `block in scope_resolving_dependency'
/Users/alec/.rvm/gems/ruby-1.9.3-p551@global/gems/librarianp-0.6.3/lib/librarian/resolver/implementation.rb:230:in `scope'
/Users/alec/.rvm/gems/ruby-1.9.3-p551@global/gems/librarianp-0.6.3/lib/librarian/resolver/implementation.rb:170:in `scope_resolving_dependency'
/Users/alec/.rvm/gems/ruby-1.9.3-p551@global/gems/librarianp-0.6.3/lib/librarian/resolver/implementation.rb:158:in `resolving_dependency_map_find_manifests'
/Users/alec/.rvm/gems/ruby-1.9.3-p551@global/gems/librarianp-0.6.3/lib/librarian/resolver/implementation.rb:65:in `do_resolve'
/Users/alec/.rvm/gems/ruby-1.9.3-p551@global/gems/librarianp-0.6.3/lib/librarian/resolver/implementation.rb:50:in `resolve'
/Users/alec/.rvm/gems/ruby-1.9.3-p551@global/gems/librarianp-0.6.3/lib/librarian/resolver.rb:23:in `resolve'
/Users/alec/.rvm/gems/ruby-1.9.3-p551@global/gems/librarianp-0.6.3/lib/librarian/action/resolve.rb:31:in `run'
/Users/alec/.rvm/gems/ruby-1.9.3-p551@global/gems/librarian-puppet-2.2.1/lib/librarian/puppet/action/resolve.rb:10:in `run'
/Users/alec/.rvm/gems/ruby-1.9.3-p551@global/gems/librarian-puppet-2.2.1/lib/librarian/puppet/cli.rb:104:in `resolve!'
/Users/alec/.rvm/gems/ruby-1.9.3-p551@global/gems/librarian-puppet-2.2.1/lib/librarian/puppet/cli.rb:68:in `install'
/Users/alec/.rvm/gems/ruby-1.9.3-p551/gems/thor-0.19.1/lib/thor/command.rb:27:in `run'
/Users/alec/.rvm/gems/ruby-1.9.3-p551/gems/thor-0.19.1/lib/thor/invocation.rb:126:in `invoke_command'
/Users/alec/.rvm/gems/ruby-1.9.3-p551/gems/thor-0.19.1/lib/thor.rb:359:in `dispatch'
/Users/alec/.rvm/gems/ruby-1.9.3-p551/gems/thor-0.19.1/lib/thor/base.rb:440:in `start'
/Users/alec/.rvm/gems/ruby-1.9.3-p551@global/gems/librarianp-0.6.3/lib/librarian/cli.rb:26:in `block (2 levels) in bin!'
/Users/alec/.rvm/gems/ruby-1.9.3-p551@global/gems/librarianp-0.6.3/lib/librarian/cli.rb:31:in `returning_status'
/Users/alec/.rvm/gems/ruby-1.9.3-p551@global/gems/librarianp-0.6.3/lib/librarian/cli.rb:26:in `block in bin!'
/Users/alec/.rvm/gems/ruby-1.9.3-p551@global/gems/librarianp-0.6.3/lib/librarian/cli.rb:47:in `with_environment'
/Users/alec/.rvm/gems/ruby-1.9.3-p551@global/gems/librarianp-0.6.3/lib/librarian/cli.rb:26:in `bin!'
/Users/alec/.rvm/gems/ruby-1.9.3-p551@global/gems/librarian-puppet-2.2.1/bin/librarian-puppet:7:in `<top (required)>'
/Users/alec/.rvm/rubies/ruby-1.9.3-p551/bin/librarian-puppet:23:in `load'
/Users/alec/.rvm/rubies/ruby-1.9.3-p551/bin/librarian-puppet:23:in `<main>'
/Users/alec/.rvm/gems/ruby-1.9.3-p551/bin/ruby_executable_hooks:15:in `eval'
/Users/alec/.rvm/gems/ruby-1.9.3-p551/bin/ruby_executable_hooks:15:in `<main>'
```

**Comment by alecswan** [comment]
Running the following command seemed to have fixed the problem:
`
librarian-puppet config use-v1-api --delete --global
`
