### ISSUE TITLE
Artifactory Unable to find module with librarian-puppet

### ISSUE THREAD

**Issue by danielserrao** [rodjek/librarian-puppet#344]
Hi,

I'm trying to use the librarian-puppet to fetch forge modules from an Artifactory repository.

In my Puppetfile I have something like:

    forge "https://<artifactory_host>/artifactory/api/puppet/<repo_key>" #From artifactory docs

    # PuppetLabs Modules
    mod 'puppetlabs/stdlib',           '4.24.0'

The command that I'm using is ``/usr/local/bin/pdk bundle -- exec librarian-puppet install --no-use-v1-api --verbose``

The error that I get is:

    [Librarian] Resolving puppetlabs-stdlib (= 4.24.0) <https://<artifactory_host>/artifactory/api/puppet/<repo_key>>
    [Librarian]   Checking manifests Unable to find module 'puppetlabs-stdlib' on https://<artifactory_host>/artifactory/api/puppet/<repo_key>
    /tmp/tmp.BXyhBoNRiR/.pdk/cache/ruby/2.1.0/gems/librarian-puppet-3.0.0/lib/librarian/puppet/source/forge/repo_v3.rb:44:in `rescue in get_module'
    /tmp/tmp.BXyhBoNRiR/.pdk/cache/ruby/2.1.0/gems/librarian-puppet-3.0.0/lib/librarian/puppet/source/forge/repo_v3.rb:41:in `get_module'

Versions:

- puppet 3.8.7
- pdk 1.5.0
- ruby 2.1.9
- librarian-puppet 0.6.4

According to the documentation at https://www.jfrog.com/confluence/display/RTF/Puppet+Repositories#PuppetRepositories-Usinglibrarian-puppet, it seems I'm trying to get the modules correctly using the librarian-puppet, but something most be missing.

I also noticed at https://www.jfrog.com/confluence/display/RTF/Puppet+Repositories that it is recommended to use Puppet version above 4.9.1 because puppet doesn't suppport context paths, but in this case changing the version is not an option. I wonder if this is really the problem.

I would like to know if there is a solution for this.

Thanks for any help.

**Comment by Xylakant** [comment]
See the Readme.md on the projects front page:

"NOTE This project has moved to https://github.com/voxpupuli/librarian-puppet"

**Comment by danielserrao** [comment]
Hi. Sorry for the late response. This is solved. The solution was to use the address ``https://<artifactory_host>/api/puppet/<repo_key>`` without the ``artifactory``.
